#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
if[[$external_monitor = *connected* ]];  then
	xrandr --output HDMI1 --primary --mode 1920x1080 --rotate normal --output eDP1 --mode 1920x1080 --rotate normal --right-of HDMI1
bspc monitor HDMI1 -d I II III IV
bspc monitor eDP1  -d  V VI VII VIII 
xrdb -load ~/.Xresources
compton &


watch -n 300 feh --randomize --bg-fill ~/Pictures/* &
